// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUR91Hf7nFo6TmeelXdMZNMnC4I9nehDo',
    appId: '1:650586806039:web:7578fbb850ee041e980952',
    messagingSenderId: '650586806039',
    projectId: 'bio-boost-lk',
    authDomain: 'bio-boost-lk.firebaseapp.com',
    storageBucket: 'bio-boost-lk.firebasestorage.app',
    measurementId: 'G-GPZZ8CFHE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCci8hXxrx3wOKq294PvU2-G7PPvlqwZQA',
    appId: '1:650586806039:android:071d68d222f9d00a980952',
    messagingSenderId: '650586806039',
    projectId: 'bio-boost-lk',
    storageBucket: 'bio-boost-lk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOrGvYGGqoMoksL5oog3wew2lpOO7A74',
    appId: '1:650586806039:ios:effdb348a1714545980952',
    messagingSenderId: '650586806039',
    projectId: 'bio-boost-lk',
    storageBucket: 'bio-boost-lk.firebasestorage.app',
    iosBundleId: 'com.example.bioBoost',
  );
}
